# authentication error messages
authentication.err.validation.authenticator.notfound=Todennus ep\u00e4onnistui, todentajaa ei l\u00f6ydy nimell\u00e4 {0}
authentication.err.validation.authenticator.notactive=Todentaja ei ole aktiivinen

authentication.err.authentication=Todennus ep\u00e4onnistui, koska k\u00e4ytt\u00e4j\u00e4nimi tai salasana on v\u00e4\u00e4rin. K\u00e4ytt\u00e4j\u00e4nimi: {0}. Syy: {1}
authentication.err.connection=Kohteeseen {0} yhdist\u00e4minen ep\u00e4onnistui, syy: {1}
authentication.err.communication=Tiedonsiirto kohteeseen {0} yhdist\u00e4minen ep\u00e4onnistui, syy: {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Yhdist\u00e4minen ep\u00e4onnistui, LDAP-is\u00e4nt\u00e4 {0} on tuntematon
authentication.err.connection.ldap.user.notfound=LDAP-k\u00e4ytt\u00e4j\u00e4\u00e4 {0} ei l\u00f6ydy
authentication.err.connection.ldap.manager.notfound=LDAP-vastaavak\u00e4ytt\u00e4j\u00e4\u00e4 {0} ei l\u00f6ydy
authentication.err.connection.ldap.search=LDAP-haku ei onnistu. Syy: {0}

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Pyynn\u00f6n vahvistaminen
authentication.step.ldap.connecting=Yhdistet\u00e4\u00e4n LDAP-palvelimeen {0}
authentication.step.ldap.connected=Yhdistet\u00e4\u00e4n LDAP-palvelimeen {0} t\u00e4ydellisell\u00e4 k\u00e4ytt\u00e4j\u00e4tunnuksella {1}
authentication.step.ldap.lookup=Hakutesti k\u00e4ytt\u00e4j\u00e4lle (userId:{0}) kyselyll\u00e4: {1}
authentication.step.ldap.lookedup=Haettiin testik\u00e4ytt\u00e4j\u00e4 userId:{0}, l\u00f6ytyi DN-nimi: {1}
authentication.step.ldap.format.user=K\u00e4ytt\u00e4j\u00e4nimimuoto m\u00e4\u00e4ritetty, userNameFormat: {2}. Muotoile k\u00e4ytt\u00e4j\u00e4n userId ({0}) tehd\u00e4ksesi DN-nimen: {1}
authentication.step.ldap.authentication=Todenna userId:{0}


# Sync Summary message 
synchronization.summary.status=K\u00e4siteltyj\u00e4 k\u00e4ytt\u00e4ji\u00e4 on {0} ja k\u00e4siteltyj\u00e4 ryhmi\u00e4 on {1}


# Error messages
authentication.ldap.validation.authenticator.notfound=Todentajaa ei l\u00f6ydy

# Synchronization Diagnostic Steps
synchronization.step.users=L\u00f6ytyi {0} k\u00e4ytt\u00e4j\u00e4\u00e4
synchronization.step.groups=L\u00f6ytyi {0} ryhm\u00e4\u00e4
synchronization.step.users.lastsynced=K\u00e4ytt\u00e4j\u00e4t synkronoitiin viimeksi {0}
synchronization.step.groups.lastsynced=Ryhm\u00e4t synkronoitiin viimeksi {0}

synchronization.err.ldap.search=LDAP-haussa tapahtui virhe. Syy: {0}
synchronization.err.ldap.get.user.id.missing=K\u00e4ytt\u00e4j\u00e4lt\u00e4 puuttuu k\u00e4ytt\u00e4j\u00e4tunnusm\u00e4\u00e4rite, DN = {0}, attributeName = {1}
synchronization.err.ldap.get.group.id.missing=Ryhm\u00e4lt\u00e4 puuttuu ryhm\u00e4tunnusm\u00e4\u00e4rite, DN = {0}, attributeName = {1}

synchronization.err.ldap.search.base.invalid=Virheellinen hakuperuste {0}, syy: {1}

synchronization.err.ldap.group.member.missing.exception=Ryhm\u00e4n j\u00e4senen {0} selvitt\u00e4minen DN-nimell\u00e4 {1} ep\u00e4onnistui, syy: {2}
synchronization.err.ldap.group.member.missing=Ryhm\u00e4n j\u00e4senen {0} selvitt\u00e4minen DN-nimell\u00e4 {1} ep\u00e4onnistui







